name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate configure script
      run: autoreconf -i

    - name: Set execute permissions for configure
      run: chmod +x ./configure

    - name: Configure the project
      run: ./configure

    - name: Build the project
      run: make
